#! /usr/bin/env mulle-bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" -o "${MULLE_RUN_TEST_TRACE}" = "YES" ] && set -x && : "$0" "$@"



MULLE_EXECUTABLE_VERSION="0.0.0"


usage()
{
   [ $# -ne 0 ] && log_error "$*"

   cat <<EOF >&2
Usage:
   ${MULLE_EXECUTABLE_NAME} [flags] -- [arguments for mulle-clang]*

   Run tests. Commands take options. Some commands take additional build and
   run options. Notice the -- separator.

Flags:
EOF

   options_technical_flags_usage " : " | sort >&2

   echo "" >&2

   exit 1
}


main()
{
   local flags
   local configuration

   flags="-O0 -g -DMULLE_TEST"
   configuration="Debug"

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help|help)
            usage
         ;;

         --rerun|--serial|--no-parallel|--parallel)
            #snarf and ignore
         ;;

         --release)
            flags="-O3 -g -DNDEBUG -DMULLE_TEST"
            configuration="Release"
         ;;

         --debug)
            flags="-O0 -g -DMULLE_TEST"
            configuration="Debug"
         ;;

         --)
            break
         ;;

         -*)
            usage "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown flag \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   local dependencydir
   local rootdir


   rootdir="${PWD}"
   dependencydir="`mulle-sde dependency-dir`" || exit 1

   local RVAL
   local sdkpath

   case "${MULLE_UNAME}" in
      darwin)
         sdkpath="-isysroot '`xcrun --show-sdk-path`'"
      ;;
   esac

   case "${MULLE_UNAME}" in
      darwin|linux)
         RPATH_FLAGS="-Wl,-rpath '${dependencydir}/${configuration}/lib' -Wl,-rpath '${dependencydir}/lib'"
      ;;
   esac


   local linkcommand

   linkcommand="`exekutor mulle-sde test linkorder --startup`" || exit 1

   log_fluff "linkorder: ${linkcommand}"

   local testfile
   local srcname
   local exename
   local directory

   shell_enable_nullglob

   #
   # MEMO not sure why we do it so strangely here with the 6-9
   #
   for testfile in `find [0-9][6-9]* -type f -name "*.m" -print`
   do
      (
         r_basename "${testfile}"
         srcname="${RVAL}"
         r_dirname "${testfile}"
         directory="${RVAL}"
         r_extensionless_basename "${testfile}"
      	exename="${RVAL}.exe"

         log_info "${srcname}"

      	cd "${directory}" &&
      	eval_exekutor mulle-clang -isystem "'${dependencydir}/${configuration}/include'" \
                                   -isystem "'${dependencydir}/include'" \
               	                 "-I'${rootdir}'" \
                                   "${sdkpath}" \
                                   -Wno-objc-root-class \
                                   -DOBJC_NO_GC \
                                   -D__OBJC2__ \
               	                 -std=gnu99 \
               	                 ${flags} \
               	                 -o "'${exename}'" \
               	                 "'${srcname}'" \
               	                 "${linkcommand}" &&
   		eval_exekutor "LD_LIBRARY_PATH='${dependencydir}/${configuration}/lib:${dependencydir}/lib'" "./'${exename}'"
      ) || exit 1
   done
}


main "$@"
