#ifndef mulle_objc_compat_include_h__
#define mulle_objc_compat_include_h__

/* This is a central include file to keep dependencies out of the library
   C files. It is usually included by .h files only.

   The advantage is that now .c and .h files become motile. They can
   be moved to other projects and don't need to be edited. Also less typing...

   Therefore it is important that this file is called "include.h" and
   not "mulle-objc-compat-include.h" to keep the #include statements in the
   library code uniform.

   The C-compiler will pick up the nearest one.
*/

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

// define some stuff, if compiling with plain C

#ifndef __MULLE_OBJC__
# define __MULLE_OBJC_TPS__
# define __MULLE_OBJC_FCS__
# ifdef DEBUG
#  define __MULLE_OBJC_TAO__
# else
#  define __MULLE_OBJC_NO_TAO__
# endif
# define __MULLE_OBJC_UNIVERSENAME__   falballa
#endif

// #include "_mulle-objc-compat-include.h"
#ifdef MULLE_OBJC_COMPAT_BUILD
# define MULLE_OBJC_COMPAT_GLOBAL    MULLE_C_GLOBAL
#else
# if defined( MULLE_OBJC_COMPAT_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE_OBJC_COMPAT_INCLUDE_STATIC))
#  define MULLE_OBJC_COMPAT_GLOBAL   MULLE_C_EXTERN_GLOBAL
# else
#  define MULLE_OBJC_COMPAT_GLOBAL   extern
# endif
#endif


#include <MulleObjC/mulle-objc.h>

#endif
