# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/objc
) 

set( OBJC_HEADERS
src/objc/Protocol.h
src/objc/message.h
src/objc/objc-abi.h
src/objc/objc-api.h
src/objc/objc-auto.h
src/objc/objc-cache.h
src/objc/objc-class.h
src/objc/objc-config.h
src/objc/objc-env.h
src/objc/objc-exception.h
src/objc/objc-gdb.h
src/objc/objc.h
src/objc/objc-internal.h
src/objc/objc-runtime.h
src/objc/objc-sync.h
src/objc/runtime.h
)

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_HEADERS
src/class.h
src/include.h
src/ivar.h
src/method.h
src/mulle-objc-compat.h
src/objc.h
src/object.h
src/property.h
src/protocol.h
src/runtime.h
src/selector.h
) 

