# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/class.c
src/method.c
src/mulle-objc-compat.c
src/object.c
src/property.c
src/protocol.c
src/selector.c
)

set( STANDALONE_SOURCES
src/mulle-objc-compat-standalone.c
)
