#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/class.m
src/method.m
src/mulle-objc-compat.m
src/object.m
src/property.m
src/protocol.m
src/runtime.m
src/selector.m
)

set( STANDALONE_SOURCES
src/mulle-objc-compat-standalone.m
)
